#!/bin/bash
#

################################################################################
# parsing options
################################################################################

set -- `getopt -qu g $@`
while [ -n $1 ]
do
    case $1 in
    -g) GEN="" ;;
    --) shift
        break ;;
    *) echo "ignoring unknown option $1" ;;
    esac
    
    shift
done

################################################################################
# execute programs
################################################################################

if [ -z $1 ]
then
    echo "Usage: vector_dominance [-g] <file_name>"
    exit 1
fi

if [ -z ${GEN+x} ]
then
	if [ -f $1 ] && [ -r $1 ]
	then	
    	java -cp VectorDominance-0.0.1.jar mx.unam.fesa.isoo.dominance.VectorDominance $1
    else
    	echo "'$1' is not a valid file"
	fi
else
	if [ -d $1 ] && [ -w $1 ]
	then
    	java -cp VectorDominance-0.0.1.jar mx.unam.fesa.isoo.dominance.TestFileGenerator $1
    	echo "test files created on '$1'"
    else
    	echo "'$1' is not a valid directory"
	fi
fi