require_relative '../lib/agent'
require_relative '../lib/board'
require_relative '../lib/client'
require_relative '../lib/core_ext'
require_relative '../lib/interpreter'
require_relative '../lib/mylogger'
require_relative '../lib/mysocket'
require_relative '../lib/play'
